# Generated by Django 4.2.3 on 2024-05-26 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ConsumerBehavior',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.CharField(max_length=10)),
                ('age', models.CharField(max_length=20)),
                ('ethnic', models.CharField(max_length=20)),
                ('occupation', models.CharField(max_length=20)),
                ('income', models.CharField(max_length=30)),
                ('use_social_media', models.CharField(max_length=5)),
                ('experience_purchasing', models.CharField(max_length=5)),
                ('reviews_affect', models.CharField(max_length=5)),
                ('internet_hours', models.CharField(max_length=20)),
                ('attention_ads', models.CharField(max_length=5)),
                ('pb1', models.IntegerField()),
                ('pb2', models.IntegerField()),
                ('pb3', models.IntegerField()),
                ('pb4', models.IntegerField()),
                ('pb5', models.IntegerField()),
                ('pb6', models.IntegerField()),
                ('t1', models.IntegerField()),
                ('t2', models.IntegerField()),
                ('t3', models.IntegerField()),
                ('t4', models.IntegerField()),
                ('t5', models.IntegerField()),
                ('c1', models.IntegerField()),
                ('c2', models.IntegerField()),
                ('c3', models.IntegerField()),
                ('c4', models.IntegerField()),
                ('c5', models.IntegerField()),
                ('pi1', models.IntegerField()),
                ('pi2', models.IntegerField()),
                ('pi3', models.IntegerField()),
                ('pi4', models.IntegerField()),
                ('pi5', models.IntegerField()),
            ],
            options={
                'verbose_name_plural': 'Consumer Behavior',
                'db_table': 'dashboard_consumerbehavior',
            },
        ),
    ]
