# Generated by Django 4.2.3 on 2024-05-26 21:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='consumerbehavior',
            old_name='c1',
            new_name='ATTD1',
        ),
        migrations.RenameField(
            model_name='consumerbehavior',
            old_name='c2',
            new_name='ATTD2',
        ),
        migrations.RenameField(
            model_name='consumerbehavior',
            old_name='c3',
            new_name='ATTD3',
        ),
        migrations.RenameField(
            model_name='consumerbehavior',
            old_name='c4',
            new_name='ATTD4',
        ),
        migrations.RenameField(
            model_name='consumerbehavior',
            old_name='c5',
            new_name='PBC1',
        ),
        migrations.RenameField(
            model_name='consumerbehavior',
            old_name='pb5',
            new_name='PBC2',
        ),
        migrations.RenameField(
            model_name='consumerbehavior',
            old_name='pb6',
            new_name='PBC3',
        ),
        migrations.RenameField(
            model_name='consumerbehavior',
            old_name='pi1',
            new_name='PBC4',
        ),
        migrations.RenameField(
            model_name='consumerbehavior',
            old_name='pi2',
            new_name='SN1',
        ),
        migrations.RenameField(
            model_name='consumerbehavior',
            old_name='pi3',
            new_name='SN2',
        ),
        migrations.RenameField(
            model_name='consumerbehavior',
            old_name='pi4',
            new_name='SN3',
        ),
        migrations.RenameField(
            model_name='consumerbehavior',
            old_name='pi5',
            new_name='SN4',
        ),
        migrations.RemoveField(
            model_name='consumerbehavior',
            name='t1',
        ),
        migrations.RemoveField(
            model_name='consumerbehavior',
            name='t2',
        ),
        migrations.RemoveField(
            model_name='consumerbehavior',
            name='t3',
        ),
        migrations.RemoveField(
            model_name='consumerbehavior',
            name='t4',
        ),
        migrations.RemoveField(
            model_name='consumerbehavior',
            name='t5',
        ),
    ]
