# Generated by Django 4.2.3 on 2024-05-28 20:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_rename_c1_consumerbehavior_attd1_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='consumerbehavior',
            old_name='pb1',
            new_name='PB1',
        ),
        migrations.RenameField(
            model_name='consumerbehavior',
            old_name='pb2',
            new_name='PB2',
        ),
        migrations.RenameField(
            model_name='consumerbehavior',
            old_name='pb3',
            new_name='PB3',
        ),
        migrations.RenameField(
            model_name='consumerbehavior',
            old_name='pb4',
            new_name='PB4',
        ),
    ]
